"""initial schema

Revision ID: 377a103a8ade
Revises: 
Create Date: 2026-05-28 18:12:47.986881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '377a103a8ade'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AIRLINES',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('NAME', sa.String(length=30), nullable=False),
    sa.Column('CODE', sa.String(length=3), nullable=False),
    sa.Column('COUNTRY', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('CODE'),
    sa.UniqueConstraint('NAME')
    )
    op.create_table('AIRPORTS',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('CODE', sa.String(length=3), nullable=False),
    sa.Column('NAME', sa.String(length=30), nullable=True),
    sa.Column('CITY', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('CODE')
    )
    op.create_table('FLIGHT_ROLES',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('ROLE_NAME', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('ROLE_NAME')
    )
    op.create_table('FLIGHT_STATUSES',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('STATUS_NAME', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('STATUS_NAME')
    )
    op.create_table('MODEL_AIRCRAFT',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('NAME', sa.String(length=30), nullable=False),
    sa.Column('MANUFACTURER', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('PEOPLE',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('LAST_NAME', sa.String(length=30), nullable=False),
    sa.Column('FIRST_NAME', sa.String(length=30), nullable=False),
    sa.Column('MIDDLE_NAME', sa.String(length=30), nullable=True),
    sa.Column('PHONE', sa.String(length=20), nullable=True),
    sa.Column('PASSPORT', sa.String(length=15), nullable=False),
    sa.Column('EMAIL', sa.String(length=100), nullable=False),
    sa.Column('PASSWORD_HASH', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('EMAIL'),
    sa.UniqueConstraint('PASSPORT')
    )
    op.create_table('SEAT_CLASSES',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('CLASS_NAME', sa.String(length=20), nullable=False),
    sa.Column('PRICE_MULTIPLIER', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('DESCRIPTION', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('CLASS_NAME')
    )
    op.create_table('SYSTEM_ROLES',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('ROLE_NAME', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('ROLE_NAME')
    )
    op.create_table('TICKET_STATUSES',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('STATUS_NAME', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('STATUS_NAME')
    )
    op.create_table('AIRCRAFT',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('REGISTRATION_NUMBER', sa.String(length=10), nullable=False),
    sa.Column('ID_MODEL', sa.Integer(), nullable=False),
    sa.Column('MANUFACTURE_YEAR', sa.Integer(), nullable=True),
    sa.Column('LAST_MAINTENANCE', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['ID_MODEL'], ['MODEL_AIRCRAFT.ID'], ),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('REGISTRATION_NUMBER')
    )
    op.create_table('CREW',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('PERSON_ID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['PERSON_ID'], ['PEOPLE.ID'], ),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('PERSON_ID')
    )
    op.create_table('MODEL_SEATS',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('ID_MODEL', sa.Integer(), nullable=False),
    sa.Column('ID_SEAT_CLASS', sa.Integer(), nullable=False),
    sa.Column('SEAT_COUNT', sa.Integer(), nullable=False),
    sa.CheckConstraint('SEAT_COUNT > 0', name='CK_SEAT_COUNT'),
    sa.ForeignKeyConstraint(['ID_MODEL'], ['MODEL_AIRCRAFT.ID'], ),
    sa.ForeignKeyConstraint(['ID_SEAT_CLASS'], ['SEAT_CLASSES.ID'], ),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('ID_MODEL', 'ID_SEAT_CLASS', name='UQ_MODEL_CLASS')
    )
    op.create_table('PEOPLE_SYSTEM_ROLES',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('PERSON_ID', sa.Integer(), nullable=False),
    sa.Column('ROLE_ID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['PERSON_ID'], ['PEOPLE.ID'], ),
    sa.ForeignKeyConstraint(['ROLE_ID'], ['SYSTEM_ROLES.ID'], ),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('PERSON_ID', 'ROLE_ID', name='UQ_PERSON_ROLE')
    )
    op.create_table('AIRCRAFT_LEASE',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('ID_AIRCRAFT', sa.Integer(), nullable=False),
    sa.Column('ID_AIRLINE', sa.Integer(), nullable=False),
    sa.Column('START_DATE', sa.Date(), nullable=False),
    sa.Column('END_DATE', sa.Date(), nullable=True),
    sa.CheckConstraint('END_DATE IS NULL OR END_DATE > START_DATE', name='CK_LEASE_DATES'),
    sa.ForeignKeyConstraint(['ID_AIRCRAFT'], ['AIRCRAFT.ID'], ),
    sa.ForeignKeyConstraint(['ID_AIRLINE'], ['AIRLINES.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('FLIGHTS',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('FLIGHT_NUMBER', sa.String(length=10), nullable=False),
    sa.Column('DEPARTURE_DATETIME', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ARRIVAL_DATETIME', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ID_FROM', sa.Integer(), nullable=False),
    sa.Column('ID_TO', sa.Integer(), nullable=False),
    sa.Column('ID_AIRLINE', sa.Integer(), nullable=False),
    sa.Column('ID_AIRCRAFT', sa.Integer(), nullable=False),
    sa.Column('ID_STATUS', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ID_AIRCRAFT'], ['AIRCRAFT.ID'], ),
    sa.ForeignKeyConstraint(['ID_AIRLINE'], ['AIRLINES.ID'], ),
    sa.ForeignKeyConstraint(['ID_FROM'], ['AIRPORTS.ID'], ),
    sa.ForeignKeyConstraint(['ID_STATUS'], ['FLIGHT_STATUSES.ID'], ),
    sa.ForeignKeyConstraint(['ID_TO'], ['AIRPORTS.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('CREW_ASSIGNMENTS',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('ID_FLIGHT_ROLE', sa.Integer(), nullable=False),
    sa.Column('ID_FLIGHT', sa.Integer(), nullable=False),
    sa.Column('ID_CREW', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ID_CREW'], ['CREW.ID'], ),
    sa.ForeignKeyConstraint(['ID_FLIGHT'], ['FLIGHTS.ID'], ),
    sa.ForeignKeyConstraint(['ID_FLIGHT_ROLE'], ['FLIGHT_ROLES.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('FLIGHT_PRICES',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('ID_FLIGHT', sa.Integer(), nullable=False),
    sa.Column('ID_SEAT_CLASS', sa.Integer(), nullable=False),
    sa.Column('PRICE', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('VALID_FROM', sa.DateTime(timezone=True), nullable=False),
    sa.Column('VALID_TO', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ID_FLIGHT'], ['FLIGHTS.ID'], ),
    sa.ForeignKeyConstraint(['ID_SEAT_CLASS'], ['SEAT_CLASSES.ID'], ),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('ID_FLIGHT', 'ID_SEAT_CLASS', 'VALID_FROM', name='UQ_FLIGHT_CLASS_DATE')
    )
    op.create_table('TICKETS',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('SEAT_NUMBER', sa.String(length=5), nullable=False),
    sa.Column('ID_SEAT_CLASS', sa.Integer(), nullable=False),
    sa.Column('PRICE', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('PURCHASE_DATE', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ID_STATUS', sa.Integer(), nullable=False),
    sa.Column('ID_FLIGHT', sa.Integer(), nullable=False),
    sa.Column('ID_PASSENGER', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ID_FLIGHT'], ['FLIGHTS.ID'], ),
    sa.ForeignKeyConstraint(['ID_PASSENGER'], ['PEOPLE.ID'], ),
    sa.ForeignKeyConstraint(['ID_SEAT_CLASS'], ['SEAT_CLASSES.ID'], ),
    sa.ForeignKeyConstraint(['ID_STATUS'], ['TICKET_STATUSES.ID'], ),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('ID_FLIGHT', 'SEAT_NUMBER', name='UQ_FLIGHT_SEAT')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TICKETS')
    op.drop_table('FLIGHT_PRICES')
    op.drop_table('CREW_ASSIGNMENTS')
    op.drop_table('FLIGHTS')
    op.drop_table('AIRCRAFT_LEASE')
    op.drop_table('PEOPLE_SYSTEM_ROLES')
    op.drop_table('MODEL_SEATS')
    op.drop_table('CREW')
    op.drop_table('AIRCRAFT')
    op.drop_table('TICKET_STATUSES')
    op.drop_table('SYSTEM_ROLES')
    op.drop_table('SEAT_CLASSES')
    op.drop_table('PEOPLE')
    op.drop_table('MODEL_AIRCRAFT')
    op.drop_table('FLIGHT_STATUSES')
    op.drop_table('FLIGHT_ROLES')
    op.drop_table('AIRPORTS')
    op.drop_table('AIRLINES')
    # ### end Alembic commands ###
